-- Etape 2
DELIMITER //
DROP TRIGGER IF EXISTS `histo_clients_M`//
CREATE TRIGGER `histo_clients_M`
    AFTER UPDATE
    ON `clients`
    FOR EACH ROW
BEGIN
    IF OLD.TELEPHONE != NEW.TELEPHONE THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE,
                                          LHEURE,
                                          UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'TELEPHONE', OLD.TELEPHONE, NEW.TELEPHONE, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;

END//
DELIMITER ;

UPDATE clients
SET TELEPHONE = '1234567890'
WHERE CODE_CLIENT = 'PNY';

-- Etape 3
DELIMITER //
DROP TRIGGER IF EXISTS histo_clients_S//
CREATE TRIGGER histo_clients_S
    AFTER DELETE
    on clients
    FOR EACH ROW
BEGIN
    INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE,
                                      UTILISATEUR)
    VALUES ('S', OLD.ID_CLIENT, 'TELEPHONE', OLD.TELEPHONE, NULL, CURDATE(), CURTIME(), CURRENT_USER());
END //
DELIMITER ;

DELETE
FROM clients
WHERE CODE_CLIENT = 'PNY';

-- Etape 4
DELIMITER //
DROP TRIGGER IF EXISTS histo_clients_C//
CREATE TRIGGER histo_clients_C
    AFTER INSERT
    ON clients
    FOR EACH ROW
BEGIN
    INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE,
                                      UTILISATEUR)
    VALUES ('C', NEW.ID_CLIENT, 'TELEPHONE', NULL, NEW.TELEPHONE, CURDATE(), CURTIME(), CURRENT_USER());

END //
DELIMITER ;

INSERT INTO clients (CODE_CLIENT, NOM_MAGASIN, ADRESSE_1, ADRESSE_2, CODE_POSTAL, VILLE, RESPONSABLE, TELEPHONE, EMAIL,
                     TYPE_CLIENT)
VALUES ('PNY', 'La boutique de Jo', 'Rue des fleurs', 'Lieu Dit les Carcasses', '48200', 'MENDE', 'M. Jo Zéphine',
        '0425676767', 'zephine@orange.fr', 3);

-- Etape 5
DELIMITER //
DROP TRIGGER IF EXISTS histo_clients_C//
CREATE TRIGGER histo_clients_C
    AFTER INSERT
    ON clients
    FOR EACH ROW
BEGIN

    INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE,
                                      UTILISATEUR)
    VALUES ('C', NEW.ID_CLIENT, 'TELEPHONE', NULL, NEW.TELEPHONE, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'CODE_CLIENT', NULL, NEW.CODE_CLIENT, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'NOM_MAGASIN', NULL, NEW.NOM_MAGASIN, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'ADRESSE_1', NULL, NEW.ADRESSE_1, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'ADRESSE_2', NULL, NEW.ADRESSE_2, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'CODE_POSTAL', NULL, NEW.CODE_POSTAL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'VILLE', NULL, NEW.VILLE, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'RESPONSABLE', NULL, NEW.RESPONSABLE, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'EMAIL', NULL, NEW.EMAIL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('C', NEW.ID_CLIENT, 'TYPE_CLIENT', NULL, NEW.TYPE_CLIENT, CURDATE(), CURTIME(), CURRENT_USER());
END //
DELIMITER ;

-- Etape 6
DELIMITER //
DROP TRIGGER IF EXISTS histo_clients_M//
CREATE TRIGGER histo_clients_M
    AFTER UPDATE
    ON clients
    FOR EACH ROW
BEGIN
    IF OLD.TELEPHONE != NEW.TELEPHONE THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'TELEPHONE', OLD.TELEPHONE, NEW.TELEPHONE, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.CODE_CLIENT != NEW.CODE_CLIENT THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'CODE_CLIENT', OLD.CODE_CLIENT, NEW.CODE_CLIENT, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.NOM_MAGASIN != NEW.NOM_MAGASIN THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'NOM_MAGASIN', OLD.NOM_MAGASIN, NEW.NOM_MAGASIN, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.ADRESSE_1 != NEW.ADRESSE_1 THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'ADRESSE_1',   OLD.ADRESSE_1, NEW.ADRESSE_1, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.ADRESSE_2 != NEW.ADRESSE_2 THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'ADRESSE_2',   OLD.ADRESSE_2, NEW.ADRESSE_2, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.CODE_POSTAL != NEW.CODE_POSTAL THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'CODE_POSTAL', OLD.CODE_POSTAL, NEW.CODE_POSTAL, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.VILLE != NEW.VILLE THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'VILLE',       OLD.VILLE, NEW.VILLE, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.RESPONSABLE != NEW.RESPONSABLE THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'RESPONSABLE', OLD.RESPONSABLE, NEW.RESPONSABLE, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.EMAIL != NEW.EMAIL THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'EMAIL',       OLD.EMAIL, NEW.EMAIL, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
    IF OLD.TYPE_CLIENT != NEW.TYPE_CLIENT THEN
        INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE, UTILISATEUR)
        VALUES ('M', NEW.ID_CLIENT, 'TYPE_CLIENT', OLD.TYPE_CLIENT, NEW.TYPE_CLIENT, CURDATE(), CURTIME(), CURRENT_USER());
    END IF;
END //
DELIMITER ;

-- Etape 7
DELIMITER //
DROP TRIGGER IF EXISTS histo_clients_S//
CREATE TRIGGER histo_clients_S
    AFTER DELETE
    ON clients
    FOR EACH ROW
BEGIN

    INSERT INTO histo_modifs_clients (MODE, ID_CLIENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR, LADATE, LHEURE,
                                      UTILISATEUR)
    VALUES ('S', OLD.ID_CLIENT, 'TELEPHONE',   OLD.TELEPHONE,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'CODE_CLIENT', OLD.CODE_CLIENT,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'NOM_MAGASIN', OLD.NOM_MAGASIN,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'ADRESSE_1',   OLD.ADRESSE_1,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'ADRESSE_2',   OLD.ADRESSE_2,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'CODE_POSTAL', OLD.CODE_POSTAL,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'VILLE',       OLD.VILLE,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'RESPONSABLE', OLD.RESPONSABLE,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'EMAIL',       OLD.EMAIL,NULL, CURDATE(), CURTIME(), CURRENT_USER()),
           ('S', OLD.ID_CLIENT, 'TYPE_CLIENT', OLD.TYPE_CLIENT,NULL, CURDATE(), CURTIME(), CURRENT_USER());
END //
DELIMITER ;
DELETE FROM clients WHERE CODE_CLIENT = 'PNY';